#!/bin/sh
#
# $Id: bashrc 760 2004-02-09 18:51:12Z blais $
# $Source$
#
# Bash configuration for this project.
#

# function ranvier-process-callgraph () {
#    source=$1
#    dest="/tmp/callgraph"
#    if [ -z "$source" ]; then
#	echo "You must specify source and destination." 1>&2
#	return
#    fi
#
#    cat $source | uniq | partorder-to-graph | dot -Tps > $dest
#    kghostview $dest
#}
#

